name: SonarCloud Analysis

on:
  push:
    branches: [main, ui-streamlit, music-reco]
  pull_request:
    branches: [main, ui-streamlit, music-reco]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies and test tools
        run: |
        
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests (backend) + coverage
        run: |
          cd backend
          PYTHONPATH=. pytest -q --maxfail=1 --disable-warnings \
            --cov=src --cov=api --cov-report=xml:coverage.xml
          test -f coverage.xml || (echo "coverage.xml manquant" && exit 1)
          cd ..
          
      - name: Show coverage file
        run: ls -l backend/coverage.xml && head -n 20 backend/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Quality Gate (PR only)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
