name: SonarCloud Analysis

on:
  push:
    branches: [main, ui-streamlit, music-reco]
  pull_request:
    branches: [main, ui-streamlit, music-reco]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies and test tools
        run: |
          python -m pip install --upgrade pip
          # Installation des dépendances du backend et des outils de test
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests (backend) + coverage
        run: |
          pytest backend -q --maxfail=1 --disable-warnings \
            --cov=backend.api --cov=backend.src --cov-report=xml:backend/coverage.xml || echo "Tests failed or not found, continuing without full coverage report."

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            # PARAMÈTRES DÉFINIS VIA CLI POUR ÉVITER D'UTILISER sonar-project.properties
            -Dsonar.projectKey=ibt2_MLOps
            -Dsonar.organization=ibt2
            -Dsonar.projectName=MLOps
            # Analyse tout le code dans le dépôt
            -Dsonar.sources=backend,ui
            -Dsonar.sourceEncoding=UTF-8
            
            # Exclusion pour l'analyse générale (très bien défini)
            -Dsonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.git/**,**/.venv/**,**/*.pkl,backend/models/**,backend/data/**,**/*.csv,*.pkl
            
            # Fichiers de couverture générés à l'étape précédente
            -Dsonar.python.coverage.reportPaths=backend/coverage.xml
            
            # Assurez-vous que le scanner ne signale pas les fichiers de tests comme "non couverts"
            -Dsonar.test.exclusions=**/tests/**,**/*test*.py 
            
            -Dsonar.python.version=3.11

      - name: SonarCloud Quality Gate (PR only)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
