name: SonarCloud
on:
  push:
    branches: [ui-streamlit, music-reco, main]
  pull_request:
    branches: [ui-streamlit, music-reco, main]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ibt2_MLOps
            -Dsonar.organization=ibt2
            -Dsonar.projectName=MLOps
            -Dsonar.sources=backend,ui
            -Dsonar.exclusions=**/__pycache__/**,**/*.pkl,backend/models/**,backend/data/**,**/*.csv,ui/.venv/**
            -Dsonar.python.version=3.11
